# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  💖 Thanks for opening this pull request! 💖
  We get a lot of pull requests on this repo, so please be patient and we will get back to you as soon as we can.

# Comment to be posted to on pull requests merged by a first time user
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉🎉🎉

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here!

# It is recommend to include as many gifs and emojis as possible
